[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Align'

[[plugins]]
repo = "vim-ruby/vim-ruby"

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'ervandew/supertab'

[[plugins]]
repo = 'ruby-matchit'

[[plugins]]
repo = 'slim-template/vim-slim'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'rodjek/vim-puppet'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'soramugi/auto-ctags.vim'

# [[plugins]]
# repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'AndrewRadev/switch.vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = "tpope/vim-endwise"

[[plugins]]
repo = "jiangmiao/auto-pairs"

[[plugins]]
repo = "pangloss/vim-javascript"

[[plugins]]
repo = "derekwyatt/vim-scala"

[[plugins]]
repo = "mxw/vim-jsx"

[[plugins]]
repo = "othree/yajs.vim"

[[plugins]]
repo = "Shougo/vimproc"
build = "make"

[[plugins]]
repo = "tpope/vim-fugitive"

[[plugins]]
repo = "scrooloose/syntastic"

[[plugins]]
repo = "pmsorhaindo/syntastic-local-eslint.vim"
