[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Align'

[[plugins]]
repo = "vim-ruby/vim-ruby"
on_ft = "ruby"

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = "ruby"

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'ervandew/supertab'

[[plugins]]
repo = 'ruby-matchit'

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = "slim"

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'rodjek/vim-puppet'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = "coffee"

[[plugins]]
repo = 'soramugi/auto-ctags.vim'

# [[plugins]]
# repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'AndrewRadev/switch.vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = "tpope/vim-endwise"

[[plugins]]
repo = "jiangmiao/auto-pairs"

[[plugins]]
repo = "pangloss/vim-javascript"
on_ft = ["javascript", "javascript.jsx"]

[[plugins]]
repo = "maxmellon/vim-jsx-pretty"
on_ft = ["javascript", "javascript.jsx"]

[[plugins]]
repo = "derekwyatt/vim-scala"
on_ft = "scala"

[[plugins]]
repo = "othree/yajs.vim"

[[plugins]]
repo = "Shougo/vimproc"
build = "make"

[[plugins]]
repo = "tpope/vim-fugitive"

[[plugins]]
repo = "kassio/neoterm"
if = '''has('nvim')'''
